namespace Agora.Agents;

/// <summary>Outcome of a single agent run: cleaned output plus extracted signals and artifacts.</summary>
public sealed record AgentResult
{
    /// <summary>Display text with control/artifact tokens stripped out.</summary>
    public required string Output { get; init; }

    /// <summary>Prompt tokens consumed by the completion.</summary>
    public int InputTokens { get; init; }

    /// <summary>Tokens generated by the completion.</summary>
    public int OutputTokens { get; init; }

    /// <summary>Prompt tokens served from the provider's cache (a subset of <see cref="InputTokens"/>).</summary>
    public int CacheReadTokens { get; init; }

    /// <summary>Prompt tokens written to the cache on this call (cache creation).</summary>
    public int CacheWriteTokens { get; init; }

    /// <summary>Control signals extracted from the output (e.g. routing decisions).</summary>
    public Dictionary<string, object> Signals { get; init; } = new();

    /// <summary>Named data artifacts extracted from the output (including <c>handoff</c>).</summary>
    public Dictionary<string, string> Artifacts { get; init; } = new();
}
